// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app.Models;

#nullable disable

namespace app.Migrations
{
    [DbContext(typeof(ConexionContext))]
    partial class ConexionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("app.Models.Asignacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("cargo_id")
                        .HasColumnType("int");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<string>("numero_colegiado")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("persona_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("cargo_id");

                    b.HasIndex("numero_colegiado")
                        .IsUnique();

                    b.HasIndex("persona_id")
                        .IsUnique();

                    b.ToTable("Asignacions");
                });

            modelBuilder.Entity("app.Models.Cargo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("nvarchar(85)");

                    b.HasKey("id");

                    b.HasIndex("nombre")
                        .IsUnique();

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("app.Models.Detalle_Vacuna", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("cantidad")
                        .HasColumnType("bigint");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("nvarchar(85)");

                    b.Property<DateTime>("fecha_vencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("vacuna_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("vacuna_id");

                    b.ToTable("Detalle_Vacunas");
                });

            modelBuilder.Entity("app.Models.Detalle_Vacunacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("asignacion_id")
                        .HasColumnType("int");

                    b.Property<int>("dosis")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_vacunacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("vacunacion_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("asignacion_id");

                    b.HasIndex("vacunacion_id");

                    b.ToTable("Detalle_Vacunacions");
                });

            modelBuilder.Entity("app.Models.Direccion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("nvarchar(85)");

                    b.HasKey("id");

                    b.HasIndex("nombre")
                        .IsUnique();

                    b.ToTable("Direccions");

                    b.HasData(
                        new
                        {
                            id = 1,
                            CreateAt = new DateTime(2023, 9, 24, 22, 59, 34, 204, DateTimeKind.Local).AddTicks(8861),
                            DeleteAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            estado = 1,
                            nombre = "Gualan"
                        },
                        new
                        {
                            id = 2,
                            CreateAt = new DateTime(2023, 9, 24, 22, 59, 34, 204, DateTimeKind.Local).AddTicks(8867),
                            DeleteAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            estado = 1,
                            nombre = "La Union"
                        },
                        new
                        {
                            id = 3,
                            CreateAt = new DateTime(2023, 9, 24, 22, 59, 34, 204, DateTimeKind.Local).AddTicks(8870),
                            DeleteAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            estado = 1,
                            nombre = "Zacapa"
                        },
                        new
                        {
                            id = 4,
                            CreateAt = new DateTime(2023, 9, 24, 22, 59, 34, 204, DateTimeKind.Local).AddTicks(8874),
                            DeleteAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            estado = 1,
                            nombre = "Rio Hondo"
                        },
                        new
                        {
                            id = 5,
                            CreateAt = new DateTime(2023, 9, 24, 22, 59, 34, 204, DateTimeKind.Local).AddTicks(8899),
                            DeleteAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            estado = 1,
                            nombre = "Estanzuela"
                        },
                        new
                        {
                            id = 6,
                            CreateAt = new DateTime(2023, 9, 24, 22, 59, 34, 204, DateTimeKind.Local).AddTicks(8903),
                            DeleteAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            estado = 1,
                            nombre = "Teculutan"
                        },
                        new
                        {
                            id = 7,
                            CreateAt = new DateTime(2023, 9, 24, 22, 59, 34, 204, DateTimeKind.Local).AddTicks(8906),
                            DeleteAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            estado = 1,
                            nombre = "Usumatlan"
                        },
                        new
                        {
                            id = 8,
                            CreateAt = new DateTime(2023, 9, 24, 22, 59, 34, 204, DateTimeKind.Local).AddTicks(8928),
                            DeleteAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            estado = 1,
                            nombre = "Huite"
                        },
                        new
                        {
                            id = 9,
                            CreateAt = new DateTime(2023, 9, 24, 22, 59, 34, 204, DateTimeKind.Local).AddTicks(8932),
                            DeleteAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            estado = 1,
                            nombre = "Cabañas"
                        },
                        new
                        {
                            id = 10,
                            CreateAt = new DateTime(2023, 9, 24, 22, 59, 34, 204, DateTimeKind.Local).AddTicks(8937),
                            DeleteAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            estado = 1,
                            nombre = "San Diego"
                        });
                });

            modelBuilder.Entity("app.Models.Genero", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("nvarchar(85)");

                    b.HasKey("id");

                    b.HasIndex("nombre")
                        .IsUnique();

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            id = 1,
                            CreateAt = new DateTime(2023, 9, 24, 22, 59, 34, 204, DateTimeKind.Local).AddTicks(9340),
                            DeleteAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            estado = 1,
                            nombre = "Masculino"
                        },
                        new
                        {
                            id = 2,
                            CreateAt = new DateTime(2023, 9, 24, 22, 59, 34, 204, DateTimeKind.Local).AddTicks(9344),
                            DeleteAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            estado = 1,
                            nombre = "Femenino"
                        });
                });

            modelBuilder.Entity("app.Models.Persona", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("cui")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("direccion_id")
                        .HasColumnType("int");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("genero_id")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("nvarchar(85)");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("id");

                    b.HasIndex("cui")
                        .IsUnique();

                    b.HasIndex("direccion_id");

                    b.HasIndex("genero_id");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            id = 1,
                            CreateAt = new DateTime(2023, 9, 24, 22, 59, 34, 204, DateTimeKind.Local).AddTicks(9468),
                            DeleteAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            cui = "111111111111",
                            direccion_id = 5,
                            estado = 2,
                            fecha_nacimiento = new DateTime(2000, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            genero_id = 1,
                            nombre = "Usuario Administrador",
                            telefono = "55353553"
                        });
                });

            modelBuilder.Entity("app.Models.Rol", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("nvarchar(85)");

                    b.HasKey("id");

                    b.HasIndex("nombre")
                        .IsUnique();

                    b.ToTable("Rols");

                    b.HasData(
                        new
                        {
                            id = 1,
                            CreateAt = new DateTime(2023, 9, 24, 22, 59, 34, 204, DateTimeKind.Local).AddTicks(9375),
                            DeleteAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            estado = 1,
                            nombre = "Administrador"
                        },
                        new
                        {
                            id = 2,
                            CreateAt = new DateTime(2023, 9, 24, 22, 59, 34, 204, DateTimeKind.Local).AddTicks(9379),
                            DeleteAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            estado = 1,
                            nombre = "Digitador"
                        },
                        new
                        {
                            id = 3,
                            CreateAt = new DateTime(2023, 9, 24, 22, 59, 34, 204, DateTimeKind.Local).AddTicks(9393),
                            DeleteAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            estado = 1,
                            nombre = "Usuario Comun"
                        });
                });

            modelBuilder.Entity("app.Models.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("correo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<string>("nombre_usuario")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("nvarchar(85)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("persona_id")
                        .HasColumnType("int");

                    b.Property<int>("rol_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("correo")
                        .IsUnique();

                    b.HasIndex("nombre_usuario")
                        .IsUnique();

                    b.HasIndex("persona_id")
                        .IsUnique();

                    b.HasIndex("rol_id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            id = 1,
                            CreateAt = new DateTime(2023, 9, 24, 22, 59, 34, 204, DateTimeKind.Local).AddTicks(9740),
                            DeleteAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            correo = "pazbryan32@gmail.com",
                            estado = 1,
                            nombre_usuario = "admin",
                            password = "$2a$11$KE1alLS08T4xNXloeDjdfOYz0Ny/aN7ikmms8.z27Unz3hztXRMgm",
                            persona_id = 1,
                            rol_id = 1
                        });
                });

            modelBuilder.Entity("app.Models.Vacuna", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("cubre")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("nvarchar(85)");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("nvarchar(85)");

                    b.Property<long>("unidades")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("nombre")
                        .IsUnique();

                    b.ToTable("Vacunas");
                });

            modelBuilder.Entity("app.Models.Vacunacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("nvarchar(85)");

                    b.Property<long>("dosis")
                        .HasColumnType("bigint");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<int>("persona_id")
                        .HasColumnType("int");

                    b.Property<int>("vacuna_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("persona_id");

                    b.HasIndex("vacuna_id");

                    b.ToTable("Vacunacions");
                });

            modelBuilder.Entity("app.Models.Asignacion", b =>
                {
                    b.HasOne("app.Models.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("cargo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("persona_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("app.Models.Detalle_Vacuna", b =>
                {
                    b.HasOne("app.Models.Vacuna", "Vacuna")
                        .WithMany()
                        .HasForeignKey("vacuna_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vacuna");
                });

            modelBuilder.Entity("app.Models.Detalle_Vacunacion", b =>
                {
                    b.HasOne("app.Models.Asignacion", "Asignacion")
                        .WithMany()
                        .HasForeignKey("asignacion_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("app.Models.Vacunacion", "Vacunacion")
                        .WithMany()
                        .HasForeignKey("vacunacion_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asignacion");

                    b.Navigation("Vacunacion");
                });

            modelBuilder.Entity("app.Models.Persona", b =>
                {
                    b.HasOne("app.Models.Direccion", "Direccion")
                        .WithMany()
                        .HasForeignKey("direccion_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.Models.Genero", "Genero")
                        .WithMany()
                        .HasForeignKey("genero_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direccion");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("app.Models.Usuario", b =>
                {
                    b.HasOne("app.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("persona_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("rol_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("app.Models.Vacunacion", b =>
                {
                    b.HasOne("app.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("persona_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("app.Models.Vacuna", "Vacuna")
                        .WithMany()
                        .HasForeignKey("vacuna_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");

                    b.Navigation("Vacuna");
                });
#pragma warning restore 612, 618
        }
    }
}
